---

- name: test block
  hosts: all

  tasks:
    - block: # try catch
      - name: debug before task failed
        debug:
          msg: "I execute normally"
      
      - name: failure
        command: /bin/echo
      rescue:
        - name: test rescue
          debug:
            msg: "I never execute, as above task is failing..."
      always:
        - name: always debug
          debug:
            msg: "this always executes"
      when: ansible_facts['distribution'] == "CentOS"

