---
- name: flask demo
  hosts: all
  # roles:
  #   - role: install_python
  tasks:
    - import_role:
        name: install-python
    - import_role:
        name: deploy-code
    - name: start flask app
      shell: nohup ~/flask-ansible-demo/.env/bin/python ~/flask-ansible-demo/wsgi.py&
      register: myoutput
    
    - name: print stdout
      debug:
        var: myoutput